Migrate Bytes to u128 internally
stratis-storage/devicemapper-rs pull request #515
Opened 2019-10-28 16:05 UTC by jbaublitz

Add support in macros for u128 internal representation in unit structs. Move `Bytes` over to u128.

There is a fair amount of added code and duplication in the macros as you cannot capture a type as a variable and then pattern match on it in a submacro so the types must be literals throughout the path travelled by the macro call stack. I would keep them all as variables if I didn't need to differentiate between `.serialize_u64()` and `.serialize_u128()` in the `serde_macro!()` body.

2019-10-30 13:33 UTC, mulkieran commented
Must defer consideration until November...

2019-11-18 16:16 UTC, mulkieran commented
Moving to December along w/ companion PR.

2019-12-12 16:08 UTC, jbaublitz commented
I've added some significant macro clean up to what I originally did.

2020-07-01 15:30 UTC, jbaublitz commented
Rebased.

2020-07-07 15:27 UTC, jbaublitz commented
CI is repeatedly failing due to #557

2020-12-05 12:45 UTC, jbaublitz commented
This should also be ready due to https://github.com/rust-lang/rfcs/pull/1504.

2021-01-04 18:02 UTC, mulkieran requested changes
This looks generally good. I'm going over Mul, Div, and Rem very closely, as they are the most tricky for dimensionality and I've noted what looks like a problem w/ ```mul``` macro.

2021-01-06 17:05 UTC, jbaublitz commented on src/range_macros.rs
> +macro_rules! mul {
This is due to `From<RangeType>` being implicitly implemented for `RangeType`, correct?

2021-01-06 17:47 UTC, mulkieran commented on src/range_macros.rs
> +macro_rules! mul {
Yes, I think that's correct.

2021-01-07 16:02 UTC, jbaublitz commented on src/range_macros.rs
> +macro_rules! mul {
Okay this should be resolved!

2021-01-07 18:12 UTC, mulkieran commented
Looks good. Moving to pending while I do review of stratisd part: https://github.com/stratis-storage/stratisd/pull/2341.

2021-01-08 15:44 UTC, mulkieran requested changes
Ok, looks ready! Please close this and open a PR for final review.

2021-01-08 15:45 UTC, closed without merging