Cleanup
stratis-storage/devicemapper-rs pull request #624
Opened 2021-04-28 22:57 UTC by jbaublitz

2021-04-29 14:17 UTC, jbaublitz commented
@mulkieran Just putting up for preliminary review. What do you think so far?

2021-04-29 15:06 UTC, mulkieran reviewed
Generally speaking, looks good to me. Have you considered generating the header file, in this case, ```dm-ioctl.h``` in the build.rs script?

2021-04-29 18:05 UTC, jbaublitz commented
Per our discussion, let's leave it as is given that the header is more configuration than code.

2021-05-03 23:20 UTC, mulkieran commented
Got the feeling that this is just about done today, so putting it in progress.

2021-05-04 14:24 UTC, jbaublitz commented
Okay, this seems to be ready for final review!

2021-05-27 06:56 UTC, flxo commented on build.rs
> +        .header("dm-ioctl.h")
`bindgen::Builder` has a nice [header_contents](https://docs.rs/bindgen/0.58.1/bindgen/struct.Builder.html#method.header_contents) fn that is perfect to avoid those small "just include something" files in the tree.

2021-05-27 12:42 UTC, mulkieran commented on build.rs
> +        .header("dm-ioctl.h")
thx for the tip!

2021-06-14 01:54 UTC, mulkieran commented on build.rs
> +        .header("dm-ioctl.h")
@jbaublitz Regarding using using ```header_contents()``` in this project; that would be fine w/ me, but also using the header file is fine w/ me.

2021-06-14 03:34 UTC, mulkieran requested changes
Looks good. Please grab commit https://github.com/stratis-storage/devicemapper-rs/pull/632/commits/699fba8fcf34959d67f110a037202ea3d63f0d65 if that looks good, and this should be ready.

2021-06-14 15:23 UTC, jbaublitz commented
@mulkieran Okay change applied!

2021-06-14 16:00 UTC, mulkieran requested changes
Looks good! Please close this and open a PR for final review.

2021-06-14 16:51 UTC, closed without merging