Add CI for musl platforms
stratis-storage/devicemapper-rs pull request #649
Opened 2021-06-25 18:25 UTC by jbaublitz

Closes #648

2021-06-26 13:10 UTC, jbaublitz commented
Re-ran tests and they passed. Putting up for review.

2021-06-27 17:30 UTC, mulkieran requested changes
Looks good. Please close this PR and open a new one for final review.

2021-06-28 05:53 UTC, flxo commented on .github/workflows/main.yml
> +        run: apk add cargo clang linux-headers make rust
nitpick: For `bindgen` we need `lib clang*.so` which is part of `libclang-dev`. `clang` itself is not needed so installing `libclang-dev` instead of `clang` safes a couple of bytes....but totally neglect able. 
Same in #649.

2021-06-28 05:53 UTC, flxo commented on .github/workflows/main.yml
> +        run: apk add cargo clang linux-headers make rust
`rust`: What's the reason to use the packaged apk instead of `actions-rs/toolchain@v1` and pull the latest stable?

2021-06-28 05:53 UTC, flxo commented on .github/workflows/main.yml
> +      - name: Test build on Alpine Linux
`make build` runs `RUSTFLAGS="${DENY}" cargo build`. Think the `name` is outdated and there's no Alpine image involved.

2021-06-28 11:44 UTC, mulkieran commented on .github/workflows/main.yml
> +        run: apk add cargo clang linux-headers make rust
I'ld be happy w/ using toolchain Action and pulling in current development toolchain, also.

2021-06-28 14:14 UTC, jbaublitz commented on .github/workflows/main.yml
> +        run: apk add cargo clang linux-headers make rust
@flxo The reason for this is that rustc does not end up in the `PATH` if installed via the toolchain action. Currently there doesn't seem to be a way to fix that as Github Actions appears to have deprecated certain ways of adding an executable to the path.

2021-06-28 14:15 UTC, jbaublitz commented on .github/workflows/main.yml
> +      - name: Test build on Alpine Linux
What do you mean? The build is happening on an Alpine Linux image.

2021-06-28 14:45 UTC, flxo commented on .github/workflows/main.yml
> +        run: apk add cargo clang linux-headers make rust
@jbaublitz Ah ok. It's just usable by the `cargo` actions then. Didn't know that.

2021-06-28 14:47 UTC, flxo commented on .github/workflows/main.yml
> +      - name: Test build on Alpine Linux
I'm confused. There's a `runs-on: ubuntu-18.04` right after `musl-checks`. The `Makefile` just calls `cargo` which must be the rust toolchain isnstalled via `apt`.

2021-06-28 15:10 UTC, jbaublitz commented on .github/workflows/main.yml
> +      image: alpine
@flxo This is the definition of the container that the build is running on. Ubuntu is just the host system because that's all that Github Actions provides.

2021-06-28 15:25 UTC, flxo commented on .github/workflows/main.yml
> +      image: alpine
@jbaublitz Thanks for the clarification!

2021-06-28 15:34 UTC, jbaublitz commented
@mulkieran I'm adding one additional change to this PR. Once CI passes, I'll open one for final review.

2021-06-28 15:43 UTC, mulkieran commented
> @mulkieran I'm adding one additional change to this PR. Once CI passes, I'll open one for final review.

@jbaublitz Ok. Test looks good.

2021-06-28 15:45 UTC, closed without merging