Default to thin pool queueing and provide behavior toggle
stratis-storage/devicemapper-rs pull request #731
Opened 2022-01-12 19:59 UTC by jbaublitz

Related to stratis-storage/stratisd#2814

2022-01-18 20:39 UTC, jbaublitz commented
Blocked by #737

2022-01-18 23:49 UTC, mulkieran requested changes
Code looks good, one request. The idea of toggling ```error_if_no_space``` is a little odd to me, I would have felt more confident with methods to set and unset it (which would have been pretty minimalist). But, go w/ toggle if you're sure that's what you want. I already looked at the source in stratisd and I understand the usage.

2022-01-18 23:49 UTC, mulkieran commented on src/thinpooldev.rs
> +    ) -> ThinPoolDevTargetTable {
Should probably have ```gen_default_table``` invoke ```gen_table```.

2022-01-19 15:31 UTC, jbaublitz commented
> Code looks good, one request. The idea of toggling error_if_no_space is a little odd to me, I would have felt more confident with methods to set and unset it (which would have been pretty minimalist). But, go w/ toggle if you're sure that's what you want. I already looked at the source in stratisd and I understand the usage.

You may have a point here mainly because I think it makes a lot of sense from the point of view of stratisd as a consumer, but maybe less sense as a general solution in a library. Let me play around with this and see what the alternative looks like.

2022-01-19 17:21 UTC, jbaublitz commented on src/thinpooldev.rs
> +    ) -> ThinPoolDevTargetTable {
Resolved!

2022-01-19 19:17 UTC, mulkieran approved these changes

2022-01-20 02:06 UTC, mulkieran commented
@jbaublitz Plz squash and merge Thursday.

2022-01-20 21:42 UTC, merged