Set a per-command ioctl version in device-mapper header
stratis-storage/devicemapper-rs pull request #770
Opened 2022-07-18 14:59 UTC by bmr-cymru

Adopt the approach taken by libdevmapper and use a table to determine
the correct ioctl interface version to specify for each possible ioctl
command.

This allows devicemapper-rs to function with a broader range of kernels
since it will only request a higher ioctl version number from the kernel
when issuing a command that requires it and avoids failures in CI test
environments where devicemapper-rs may be built with newer device-mapper
features than are supported by the running kernel.

2022-07-18 15:03 UTC, bmr-cymru commented on src/core/dm.rs
> +        }
This keeps the old behaviour of using the compiled-against libdevmapper ioctl version for unknown commands, but I'm leaning toward thinking that we should instead treat that as an error condition?

2022-07-18 15:12 UTC, bmr-cymru commented
It's easy enough to trim the table down by special-casing the original v4 commands, but it feels a bit like deckchair shuffling:

```rust
const CMD_VERSIONS: [(u32, u32, u32); 5] = [
    (4, 1, 0),
    (4, 2, 0),
    (4, 6, 0),
    (4, 36,0),
    (4, 41, 0),
];

fn ioctl_version_for_cmd(cmd: u8) -> Option<(u32, u32, u32)> {
    if cmd <= dmi::DM_TABLE_STATUS_CMD as u8 {
        Some((4, 0, 0))
    } else if cmd <= dmi::DM_GET_TARGET_VERSION_CMD as u8 {
        let idx = cmd as usize - dmi::DM_LIST_VERSIONS_CMD as usize;
        Some(CMD_VERSIONS[idx])
    } else {
        None
    }
}
```

It would be helpful if libdevmapper had boundary constants for the ioctl commands and I'm wondering if the table couldn't be generated automatically from the generated bindings somehow? I'm fairly limited in bingden knowledge but I'll take a look at this now.

2022-07-18 15:18 UTC, bmr-cymru commented
The CI tests have revealed another drawback with the simple approach:

```
   Compiling cexpr v0.6.0
   Compiling nix v0.24.2
   Compiling devicemapper-sys v0.1.2 (/__w/devicemapper-rs/devicemapper-rs/devicemapper-rs-sys)
   Compiling devicemapper v0.32.0 (/__w/devicemapper-rs/devicemapper-rs)
error[E0425]: cannot find value `DM_GET_TARGET_VERSION_CMD` in module `dmi`
   --> src/core/dm.rs:102:20
    |
102 |     if cmd <= dmi::DM_GET_TARGET_VERSION_CMD as u8 {
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `dmi`
```

The copy of libdevmapper used in this CI environment pre-dates the introduction of this ioctl command:

```
-=================================
+Version 1.02.165 - 23rd October 2019
+====================================
   Add support for DM_DEVICE_GET_TARGET_VERSION.
   Add debug of dmsetup udevcomplete with hexa print DM_COOKIE_COMPLETED.
   Fix versioning of dm_stats_create_region and dm_stats_create_region.
```

Which means that devicemapper-rs cannot use the symbolic name without triggering a build error (A `DM_IOCTL_CMD_MAX` would be helpful here!).

2022-07-18 17:00 UTC, bmr-cymru commented on src/core/dm.rs
> +        }
v2 now treats unknown command values as errors.

2022-07-18 20:07 UTC, mulkieran requested changes
I'm definitely happy with this change overall, but have a few comments and suggestions.

2022-07-18 20:07 UTC, mulkieran commented on src/core/dm.rs
> +
I was going to ask you not to separate the comment chunk from its neighbor, but you can just get rid of the whole comment, both chunks, instead. The whole comment here is obsolete or duplicated elsewhere.

2022-07-19 12:49 UTC, mulkieran approved these changes
Looks good!

2022-07-19 16:17 UTC, jbaublitz requested changes
@mulkieran I requested that @bmr-cymru try taking a feature flagging approach for constants in devicemapper-rs like we do in libcryptsetup-rs based on the version. We should be able to both use the header versions to determine feature flags while also using the table to use the minimum accepted version like `libdm` to avoid kernel/userspace header mismatch problems.

2022-07-20 16:26 UTC, bmr-cymru commented on src/core/dm.rs
> +        None
Thanks! I actually had the function returning just a tuple at one point, but it didn't occur to me how to handle the unreachable branch.

2022-07-20 16:26 UTC, bmr-cymru commented on src/core/dm.rs
> +
Removed in updated branch.

2022-07-20 16:41 UTC, mulkieran requested changes
One thing I just noticed, otherwise looks good.

2022-07-20 16:41 UTC, mulkieran commented on src/core/dm.rs
> +    #[cfg(devicemapper46supported)]
I think this should properly be "41" not "46".

2022-07-20 17:05 UTC, bmr-cymru commented on src/core/dm.rs
> +    #[cfg(devicemapper46supported)]
Thank you!

2022-07-20 17:11 UTC, bmr-cymru commented
I've rebased again to fix the problem @mulkieran pointed out - originally i was only generating feature flags as far back as devicemapper46supported. When I amended build.rs to also generate the older flags I neglected to fix up the feature flags in dm.rs to use the correct versioning.

2022-07-20 19:41 UTC, mulkieran approved these changes

2022-07-20 21:17 UTC, jbaublitz approved these changes

2022-07-20 22:15 UTC, merged