Do ioctl
stratis-storage/devicemapper-rs pull request #806
Opened 2022-12-12 22:44 UTC by mulkieran

2022-12-20 15:22 UTC, jbaublitz requested changes
Two comments, but other than that, this looks good.

2022-12-20 15:22 UTC, jbaublitz commented on src/core/dm.rs
> +            buffer.resize((len as u32).saturating_mul(2) as usize, 0);
As I mentioned previously, I don't think doubling the size makes sense when devicemapper explicitly returns the size required to fit the message. We could simply use the output `data_size` which I think is simpler and will result in a maximum of two iterations.

2022-12-20 15:22 UTC, jbaublitz commented on src/core/dm.rs
> +        let data_end = cmp::max(buffer_hdr.data_size, buffer_hdr.data_start);
Should this be `data_size + data_start`? I'm not sure `max()` does what we want in the case where `data_size < data_start` but still nonzero. This seems like it would truncate the data.

2022-12-20 18:45 UTC, mulkieran commented on src/core/dm.rs
> +            buffer.resize((len as u32).saturating_mul(2) as usize, 0);
I don't think we can rely on that. Take a look at the implementation of ```target_message```. We see:

```
        if (r == 1) {
                param->flags |= DM_DATA_OUT_FLAG;
                if (dm_message_test_buffer_overflow(result, maxlen))
                        param->flags |= DM_BUFFER_FULL_FLAG;
                else
                        param->data_size = param->data_start + strlen(result) + 1;
                r = 0;
        }
```

2022-12-20 18:50 UTC, mulkieran commented on src/core/dm.rs
> +        let data_end = cmp::max(buffer_hdr.data_size, buffer_hdr.data_start);
I don't know why data_size is sometimes set to less than data_start, so max seems necessary. data_size always includes the length of the hdr, which is data_start.

2022-12-21 17:36 UTC, mulkieran commented on src/core/dm.rs
> +        let data_end = cmp::max(buffer_hdr.data_size, buffer_hdr.data_start);
Ok. I believe it's clear why ```data_size``` is sometimes set to less than ```data_start```.  Before the selected ioctl computations are done, ```data_size``` is set to the offset to the start of the ```data``` field in in the dm_ioctl struct, which is 7 bytes less than the size of the whole struct. This is born out by tests. The message stratisd sends always sets ```data_start``` to the size of the whole struct. I do not believe that the data field is every actually used, it seems to function just as padding.

2022-12-21 20:42 UTC, jbaublitz commented on src/core/dm.rs
> +        let data_end = cmp::max(buffer_hdr.data_size, buffer_hdr.data_start);
This makes sense!

2022-12-21 20:48 UTC, jbaublitz commented on src/core/dm.rs
> +            buffer.resize((len as u32).saturating_mul(2) as usize, 0);
It looks like I was totally wrong after looking at the kernel code. It appears it only sets the `data_size` parameter not only there but *everywhere* on success and on failure, it isn't touched. Resolving this.

2022-12-21 20:48 UTC, jbaublitz approved these changes
This looks reasonable to me!

2022-12-22 03:04 UTC, mulkieran commented
Rewrite buffer management commit msg was slightly out of date wrt. the commit.

2022-12-22 14:49 UTC, bgurney-rh approved these changes

2022-12-22 14:50 UTC, merged