Downgrade DM debugging messages to trace level
stratis-storage/devicemapper-rs pull request #890
Opened 2023-11-07 18:07 UTC by bmr-cymru

Commit 66e1fdf2 added logging to the DM module using the debug! macro.

In practice these messages can be very noisy, especially for e.g. in the Stratis test suite (which calls the status() method on thin pool devices). This leads to lots of messages like the following:

[2023-11-06T16:01:05Z DEBUG devicemapper::core::dm] Retrieving table status for stratis-1-private-50db9929d265403b820bb155c8f5ae89-thinpool-pool

Running the Stratis test suite results in hundreds of these messages being logged at debug level.

Downgrade the logging calls in the DM module from debug! to trace! to quiet this down.

2023-11-08 03:15 UTC, mulkieran approved these changes
This is fine w/ me, although if you wanted to leave the bigger actions, create, rename, remove at debug level, I would be fine w/ that also.

2023-11-08 03:15 UTC, mulkieran commented on src/core/dm.rs
> +        trace!("Clearing inactive dable for {}", id);
Might as well fix typo also: ^dable^table

2023-11-08 03:18 UTC, mulkieran requested changes
Forgot about the typo...definitely should fix that.

2023-11-08 13:46 UTC, bmr-cymru commented on src/core/dm.rs
> +        trace!("Clearing inactive dable for {}", id);
Well spotted, thanks!

2023-11-08 14:34 UTC, jbaublitz approved these changes

2023-11-08 14:42 UTC, bmr-cymru commented
> This is fine w/ me, although if you wanted to leave the bigger actions, create, rename, remove at debug level, I would be fine w/ that also.

I think that would make sense. Those operations should be considerably less frequent in any case. I'll update the PR.

2023-11-08 14:45 UTC, bmr-cymru commented
I've revised this to leave the create, remove, rename, suspend/resume and target message logs at debug level with the rest downgraded to trace.

2023-11-09 19:14 UTC, mulkieran approved these changes

2023-11-09 19:14 UTC, merged